de: Hallo! Wie kann ich Ihnen heute helfen?
en: Hello! How can I help you today?
es: ¡Hola! ¿En qué te puedo ayudar?
fr: Bonjour ! Comment puis-je vous aider aujourd’hui ?
fr-CA: Bonjour! Comment puis-je vous aider aujourd’hui?
hi: नमस्ते! आज मैं आपकी कैसे मदद कर सकता हूँ?
ko: 안녕하세요! 오늘 무엇을 도와드릴까요?
